---
title: "Provincial Site Productivity Layer Version 9.0"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

## Background

The **Provincial Site Productivity Layer (PSPL)** provides **area-based site index estimates** for **14 commercial tree species across British Columbia (BC)**. The PSPL v.9.0 was developed and is managed by the Forest Analysis and Inventory Branch (FAIB) to address several limitations of PSPL v.8.0 by: 1) reducing discrepancies between PSPL estimates and field-measured site productivity, 2) filling gaps in estimates across large areas, and 3) establishing a more systematic and updateable modelling framework.  

PSPL v.9.0 adopts a machine learning-based *Random Forest (RF) modelling approach* that incorporates climatic, topographic, and ecosystem classification predictor variables. More than 13,000 ground-based site index observations from *FAIB ground sampling inventories, Site Index Biogeoclimatic Ecosystem Classification (SIBEC), and Site Index Adjustment (SIA) projects* were used to develop and validate the models. Validation results demonstrated that PSPL v.9.0 outperformed the previous v.8.0 in site index prediction accuracy for all species except black spruce, with particularly strong improvements for key commercial species including *Douglas-fir, lodgepole pine, western hemlock, western redcedar, and subalpine fir*. The new PSPL also establishes a reproducible and scalable predictive modelling framework that provides wall-to-wall coverage across BC at a **100 × 100 m spatial resolution**.


## Open Data

The PSPL v.9.0 is publicly available via [BC Data Catalogue](https://catalogue.data.gov.bc.ca/dataset/04ad45c3-0fdc-4506-bdb4-252c45a63459) subject to the [Open Government Licence - British Columbia](https://www2.gov.bc.ca/gov/content/data/policy-standards/data-policies/open-data/open-government-licence-bc).  


## References

For more info, visit [Provincial Site Productivity Layer webpage](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/site-productivity/provincial-site-productivity-layer).  


## Purpose of Web App

This web-based application was developed to facilitate custom queries and downloads of PSPL v.9.0 estimates for user-defined locations or areas of interest.  


### Example 


